
openapi: 3.1.0
info:
  title: BotCrafterController API
  version: 1.0.0
  description: Vollständiges OpenAPI-Schema der BotCrafterController-Anwendung.
servers:
  - url: https://botcraftercontroler-5317cefda72b.herokuapp.com/api
    description: Produktionsserver
  - url: http://localhost:5000
    description: Lokaler Entwicklungsserver
paths:
  /list-files:
    get:
      operationId: listFiles
      summary: Listet Dateien im Google Drive auf.
      description: Gibt eine Liste von Dateien im angegebenen Ordner zurück.
      parameters:
        - name: folder_id
          in: query
          required: false
          description: ID des Ordners im Google Drive.
          schema:
            type: string
      responses:
        "200":
          description: Erfolgreiche Antwort mit Dateiliste.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileListResponse'
  /upload-file:
    post:
      operationId: uploadFile
      summary: Lädt eine Datei in Google Drive hoch.
      description: Die Datei wird in das angegebene Verzeichnis hochgeladen.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadFileRequest'
      responses:
        "201":
          description: Datei erfolgreich hochgeladen.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadFileResponse'
  /delete-file:
    delete:
      operationId: deleteFile
      summary: Löscht eine Datei aus Google Drive.
      description: Entfernt die Datei anhand ihrer ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteFileRequest'
      responses:
        "204":
          description: Datei erfolgreich gelöscht.
  /list-repos:
    get:
      operationId: listRepositories
      summary: Listet alle verfügbaren Repositories aus der Konfiguration auf.
      description: Gibt die Namen und URLs der verfügbaren Repositories zurück.
      responses:
        "200":
          description: Erfolgreiche Antwort mit Liste von Repository-Namen.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositoryListResponse'
  /routes:
    get:
      operationId: listRoutes
      summary: Listet alle verfügbaren Routen der API auf.
      description: Gibt eine Liste aller API-Endpunkte mit ihren Methoden zurück.
      responses:
        "200":
          description: Erfolgreiche Antwort mit Liste von Routen.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoutesListResponse'
components:
  schemas:
    FileListResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            description: Die eindeutige ID der Datei.
          name:
            type: string
            description: Der Name der Datei.
    UploadFileRequest:
      type: object
      properties:
        file_path:
          type: string
          description: Der Pfad zur hochzuladenden Datei.
        mime_type:
          type: string
          description: Der MIME-Typ der Datei.
        parent_folder_id:
          type: string
          description: Die ID des übergeordneten Ordners.
    UploadFileResponse:
      type: object
      properties:
        id:
          type: string
          description: Die ID der hochgeladenen Datei.
        name:
          type: string
          description: Der Name der hochgeladenen Datei.
    DeleteFileRequest:
      type: object
      properties:
        file_id:
          type: string
          description: Die ID der zu löschenden Datei.
    RepositoryListResponse:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            description: Der Name des Repositories.
          url:
            type: string
            description: Die URL des Repositories.
    RoutesListResponse:
      type: array
      items:
        type: object
        properties:
          route:
            type: string
            description: Der Pfad der Route.
          methods:
            type: array
            items:
              type: string
            description: Die HTTP-Methoden, die von der Route unterstützt werden.
security:
  - api_key: []
securitySchemes:
  api_key:
    type: apiKey
    in: header
    name: Authorization
