
openapi: 3.1.0
info:
  title: BotCrafterController API
  version: 1.0.0
  description: Vollständiges OpenAPI-Schema der BotCrafterController-Anwendung.
servers:
- url: https://botcraftercontroler-5317cefda72b.herokuapp.com/api
    description: Produktionsserver
  - url: http://localhost:5000
    description: Lokaler Entwicklungsserver
paths:
  /list-files:
    get:
      summary: Listet Dateien im Google Drive auf.
      description: Gibt eine Liste von Dateien im angegebenen Ordner zurück.
      parameters:
        - name: folder_id
          in: query
          required: false
          description: ID des Ordners im Google Drive.
          schema:
            type: string
      responses:
        "200":
          description: Erfolgreiche Antwort mit Dateiliste.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Die eindeutige ID der Datei.
                    name:
                      type: string
                      description: Der Name der Datei.
  /upload-file:
    post:
      summary: Lädt eine Datei in Google Drive hoch.
      description: Die Datei wird in das angegebene Verzeichnis hochgeladen.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_path:
                  type: string
                  description: Der Pfad zur hochzuladenden Datei.
                mime_type:
                  type: string
                  description: Der MIME-Typ der Datei.
                parent_folder_id:
                  type: string
                  description: Die ID des übergeordneten Ordners.
      responses:
        "201":
          description: Datei erfolgreich hochgeladen.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Die ID der hochgeladenen Datei.
                  name:
                    type: string
                    description: Der Name der hochgeladenen Datei.
  /delete-file:
    delete:
      summary: Löscht eine Datei aus Google Drive.
      description: Entfernt die Datei anhand ihrer ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_id:
                  type: string
                  description: Die ID der zu löschenden Datei.
      responses:
        "204":
          description: Datei erfolgreich gelöscht.
  /list-repos:
    get:
      summary: Listet alle verfügbaren Repositories aus der Konfiguration auf.
      description: Gibt die Namen und URLs der verfügbaren Repositories zurück.
      responses:
        "200":
          description: Erfolgreiche Antwort mit Liste von Repository-Namen.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Der Name des Repositories.
                    url:
                      type: string
                      description: Die URL des Repositories.
  /routes:
    get:
      summary: Listet alle verfügbaren Routen der API auf.
      description: Gibt eine Liste aller API-Endpunkte mit ihren Methoden zurück.
      responses:
        "200":
          description: Erfolgreiche Antwort mit Liste von Routen.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    route:
                      type: string
                      description: Der Pfad der Route.
                    methods:
                      type: array
                      items:
                        type: string
                      description: Die HTTP-Methoden, die von der Route unterstützt werden.
